language: node_js
sudo: required
dist: xenial

node_js:
 - "8"
 - "10"

branches:
  only:
    - master

services:
  - mysql

install:
 - npm install

before_install:
 - mysql -e 'CREATE DATABASE IF NOT EXISTS idm;' 
 - mysql -u root --default-character-set=utf8 idm < test/mysql-data/backup.sql

# before_script:
 # - npm run lint

after_script: 
  - npm run test:coveralls

