language: node_js
sudo: required

node_js:
 - "8"
 - "10"

branches:
  only:
    - master

services:
  - docker

install:
 - npm install

before_install:
 - docker pull mysql:5.7
 - docker run -d -l mysql -p 3306:3306 -v $(pwd)/test/mysql-data:/docker-entrypoint-initdb.d/:ro -e MYSQL_ROOT_PASSWORD=test mysql:5.7

# before_script:
 # - npm run lint

after_script: 
  - npm run test:coveralls

