site_name: Fiware-IdM
site_url: http://fiware-idm.readthedocs.org
repo_url: https://github.com/ging/fiware-idm
site_description: Identity Management Keyrock Documentation
docs_dir: doc
site_dir: html
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_security.css"]
#google_analytics: ['UA-******', 'fiware-idm.readthedocs.io']