site_name: Fiware-IdM
site_url: http://mesias.readthedocs.org
repo_url: https://github.com/ging/mesias
site_description: Identity Management Keyrock Documentation
docs_dir: doc
site_dir: html
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
#google_analytics: ['UA-******', 'fiware-idm.readthedocs.io']